### ISSUE TITLE
2.1.0 give in_array(): Argument #2 ($haystack) must be of type array, string given exception

### ISSUE THREAD

**Issue by ziming** [Propaganistas/Laravel-Disposable-Email#22]
I got the following error in the latest version (2.1.0). Downgrading to 2.0.19 fixes it

in_array(): Argument #2 ($haystack) must be of type array, string given

```php
public function isDisposable($email)
    {
        if ($domain = Str::lower(Arr::get(explode('@', $email, 2), 1))) {
            return in_array($domain, $this->domains); // This line

```

**Comment by Propaganistas** [comment]
Thanks for reporting. I'm puzzled how it's possible that `$this->domains` ends up being a string. It might be worth to check your cache contents, storage contents or list source's response...

I've implemented a safeguard anyway. Could you please update to 2.1.1?

**Comment by ziming** [comment]
Hi @Propaganistas 

I just did a composer update and test it locally again. I still get that exception. I went into the logs and see this

```
#0 /Users/my-username/php-apps/app-name/vendor/propaganistas/laravel-disposable-email/src/DisposableDomains.php(170): in_array('gmail.com', '[\".\",\".impo-tex...')
```

If it helps I'm on PHP 8

**Comment by Propaganistas** [comment]
Can you update again to 2.1.3?

**Comment by ziming** [comment]
it looks like 2.1.2 fixed it. Haven't try 2.1.3 yet
